version: "3.9"
services:
  javari-frontend:
    container_name: javari-front
    image: node:alpine
    ports:
      - "3000:3000"
  javari-db:
    container_name: javari-db
    image: mysql:latest
    networks:
      - javari-backend
networks:
  javari-backend:
    driver: bridge
