version: "3.9"
services:
  javari-frontend:
    container_name: javari-front
    image: node:alpine
    ports:
      - "3000:3000"
    networks:
      - javari-front
      - javari-db
  javari-db:
    container_name: javari-db
    image: mysql:latest
    networks:
      - javari-db
networks:
  javari-front:
    driver: bridge
  javari-db:
    driver: bridge
